# Assignment 1

In [2]:
import numpy as np
import timeit 
from numpy.lib.stride_tricks import as_strided

## Create Numpy Arrays

### 1). Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array. 

In [2]:
x=[[1,2,3],[4,5,6]]
array=np.array(x)
print ("Desired Numpy array :\n", array)

Desired Numpy array :
 [[1 2 3]
 [4 5 6]]


In [3]:
x = [[1,2,3],[4,5,6]]
array = np.array(x)
print(array)

[[1 2 3]
 [4 5 6]]


### 2). Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6.

In [3]:
x=np.arange(1,7).reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.array([range(i, i +3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 3). Create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.

In [4]:
x=np.arange(2,101,2)
y=x.mean()
print("Array : \n",x)
print()
print("Mean : \n",y)

Array : 
 [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

Mean : 
 51.0


In [27]:
#creating the array with linear sequenece 
# arrange(start,end,step)
x=np.arange(1,100,3)
x

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [30]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
np.ones(10, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.

### 4). Create an 3x3x3 array filled with arbitrary values; and find the minimum and maximum values.

In [5]:
x=np.random.rand(3,3,3)
y=x.min()
z=x.max()
print("Array : \n",x)
print("Minimum value : \n",y)
print("Maximum value : \n",z)

Array : 
 [[[0.43025441 0.57111655 0.70187093]
  [0.55867705 0.1117936  0.59858122]
  [0.95775516 0.31146941 0.44761715]]

 [[0.78915531 0.02386237 0.41893582]
  [0.34600979 0.77587629 0.85034771]
  [0.68559503 0.65899465 0.47438817]]

 [[0.4682919  0.31071026 0.06654176]
  [0.97227261 0.70761079 0.15142714]
  [0.19388189 0.95314977 0.96814691]]]
Minimum value : 
 0.023862371123979487
Maximum value : 
 0.9722726086310376


### 5). Create a random array of size 10 and sort it.

In [6]:
x=np.random.randint(10,size=10)
y=np.sort(x)
print("Sorted Array : ",y)

Sorted Array :  [0 0 3 4 5 5 6 8 8 9]


### 6). Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [7]:
a=10
b=np.linspace(5,5+(a*3),10,dtype=int,endpoint=False)
b


array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### 7). Create an arbitrary array of shape (10,10); and find the memory size of this array.

In [8]:
a=np.random.rand(10,10)
b=a.nbytes                               
print("Arbiratry array :\n",a)
print("\nMemory size in bytes:\n",b) 

Arbiratry array :
 [[0.17200619 0.67311347 0.58712728 0.98652445 0.30777488 0.64151206
  0.41686062 0.11887099 0.90460329 0.82879313]
 [0.37515782 0.9141385  0.01521914 0.72794316 0.49328908 0.81500008
  0.63283454 0.96718511 0.62452785 0.73971586]
 [0.78064921 0.57038815 0.26788488 0.02246441 0.49364902 0.26399356
  0.80260696 0.54549694 0.2931666  0.33994112]
 [0.43236237 0.9214464  0.06700777 0.61688235 0.832049   0.27673179
  0.69942332 0.17282844 0.38512729 0.43635609]
 [0.78034991 0.44413667 0.06288114 0.23464479 0.89183849 0.97162596
  0.95871921 0.31669571 0.49476253 0.36056446]
 [0.94068872 0.61430031 0.55005848 0.1576021  0.06709428 0.72100306
  0.78747374 0.3618591  0.82293303 0.18025375]
 [0.66838053 0.88048577 0.01562388 0.88775943 0.13569019 0.29360029
  0.71481978 0.48209892 0.83441384 0.93121368]
 [0.72536954 0.5831644  0.27910348 0.28821124 0.94572851 0.89351553
  0.14956781 0.23421916 0.94747604 0.98487504]
 [0.35770766 0.04919563 0.61669576 0.61567017 0.90770709 0.70

### 8). Create a null array of size 10 but the fifth value which is 1.

In [9]:
np.array([int(a==4) for a in range(10)])  

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 9). Create an array with values ranging from 10 to 49; and reverse it then (first element becomes last). 

In [10]:
x=np.arange(10,50)
y=np.flip(x,0)
print("Array : \n",x)
print("Reversed Array : \n",y)

Array : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed Array : 
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 10). Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.

In [11]:
np.random.seed(0)
x=np.random.uniform(0,1,size=(3,2))
print("Array : \n",x)

Array : 
 [[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]


### 11). Create a 5x5 matrix with row values ranging from 0 to 4:                                2 points

[[0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]]

In [12]:
x = np.zeros((5,5))
x+=np.arange(5)                   
x


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 12). Add a border (filled with 0's) around an existing array:                                     4 points

[[1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]]

---->>

[[0. 0. 0. 0. 0. 0. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 0. 0. 0. 0. 0. 0.]]

In [13]:
x=np.ones((5,5))
print("Original array :\n",x)
y=np.pad(x,(1,1),'constant',constant_values=0)
print("Array with 0's border: \n",y)



Original array :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array with 0's border: 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 13). Create a 5x5 2D array with values 1,2,3,4,5 on the diagonal                 4 points

[1 0 0 0 0]

 [0 2 0 0 0]

 [0 0 3 0 0]

 [0 0 0 4 0]

 [0 0 0 0 5]]

Then, make 1,2,3,4 move below the diagonal:

[[0 0 0 0 0]

 [1 0 0 0 0]

 [0 2 0 0 0]

 [0 0 3 0 0]

 [0 0 0 4 0]]

In [14]:
x=np.zeros((5,5))
x[[0,1,2,3,4],[0,1,2,3,4]]=1,2,3,4,5
print(x)
x= np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x[0:-2,1:-1])

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


### 14). Create a 2d 10x10 array with 1 on the border and 0 inside.                  4 points

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [15]:
x=np.zeros((8,8))
y=np.pad(x,(1,1),'constant',constant_values=1)
print("Array with 1's border : \n",y)


Array with 1's border : 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 15). Extract the integer part of a random array of positive numbers using 2 different methods, and the result should be an integer array.                2 points

In [16]:
arr = np.random.uniform(0,10,size=(10))
print(arr)
print("1st Method :",np.asarray(arr,dtype=int))
print("2nd Method : ",arr.astype(int))

[4.37587211 8.91773001 9.63662761 3.83441519 7.91725038 5.2889492
 5.68044561 9.25596638 0.71036058 0.871293  ]
1st Method : [4 8 9 3 7 5 5 9 0 0]
2nd Method :  [4 8 9 3 7 5 5 9 0 0]


# Operations on Numpy Arrays: 

### 1). Find the index of 5th repetition of number 1 in the given array x.          2 points

x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]

In [17]:
x=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
output=np.where(x==1)
output[0][4]

8

### 2). Use arange to get an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [18]:
x=np.arange(1,10)
x
y1,y2,y3=np.split(x,[4,6])
print("1st array: \n",y1,"\n 2nd array:\n",y2,"\n3rd array: \n",y3)


1st array: 
 [1 2 3 4] 
 2nd array:
 [5 6] 
3rd array: 
 [7 8 9]


### 3). Use arange to generate the following 2D array:               2 points

[[ 0., 1., 2., 3.],

 [ 4., 5., 6., 7.],

 [ 8., 9., 10., 11.],

 [ 12., 13., 14., 15.]]

Use np.split to split the array into left and right halves.

[[ 0,  1],

 [ 4,  5],

 [ 8,  9],

 [12, 13]]

and

[[ 2,  3],

 [ 6,  7],

 [10, 11],

 [14, 15]]

In [19]:
x=np.arange(16).reshape(4,4)
print("2D Array :",x)
split1,split2=np.hsplit(x,2)
print("Splitted Arrays : ")
print("Split1 : \n",split1,"\n Split2 :\n",split2)

2D Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Splitted Arrays : 
Split1 : 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 Split2 :
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### 4). Given an 2D array:                                                 2 points

[[5,10,15],

 [20,25,30],

 [35,40,45]]

(1) Slicing to get the sub-array [[10,15], [25,30]]

(2) Getting individual element value "20"

In [20]:
x=np.array([[5,10,15],

 [20,25,30],

 [35,40,45]])
subarray=x[:2,1:]
element=x[1,0]
print("Individual element :" ,element)
print("Sliced :\n",subarray)


Individual element : 20
Sliced :
 [[10 15]
 [25 30]]


### 5). Let x be an array:                                                  

[[ 1 2 3],

 [ 4 5 6]].

and y be an array

[[ 7 8 9],

 [10 11 12]].

Concatenate x and y so that a new array looks like

[[1, 2, 3, 7, 8, 9],

 [4, 5, 6, 10, 11, 12]].

In [21]:
x=np.array([[ 1, 2, 3], [ 4, 5, 6]])
y=np.array([[ 7 ,8 ,9], [10 ,11 ,12]])       
z=np.concatenate([x,y],axis=1)
z

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 6). Compute the min/max (min is divided by max) for each row for a given 2d array, in which integer values range from 1 to 10 [1,10) and shape is (5,3).

Here requires a random seed to keep the same value from the random generator.

In [22]:
np.random.seed(10) 
y = np.random.randint(1,10, size=(5, 3))
print(y)
ymax=np.amax(y,axis=1)           
ymin=np.amin(y,axis=1)
xy=ymin/ymax
print(xy)

[[5 1 2]
 [1 2 9]
 [1 9 7]
 [5 4 1]
 [5 7 9]]
[0.2        0.11111111 0.11111111 0.2        0.55555556]


### 7). Normalize a 5x5 random matrix:                          2 points

Tips: a normalization operates like: (the array - the mean)/the standard deviation

In [23]:
x= np.random.random((5,5))
print("Original Array :")
print(x)
y=np.mean(x)
z=np.std(x)
result=(x-y)/z                               
result

Original Array :
[[0.81262096 0.61252607 0.72175532 0.29187607 0.91777412]
 [0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718]
 [0.60103895 0.8052232  0.52164715 0.90864888 0.31923609]
 [0.09045935 0.30070006 0.11398436 0.82868133 0.04689632]]


array([[ 1.15446266,  0.36536391,  0.79612285, -0.89915868,  1.56914705],
       [ 0.76780948,  0.0893825 , -1.48954273, -0.57789268,  0.60832083],
       [-0.30778445, -0.33862035,  0.38603208, -0.02658417,  0.51471329],
       [ 0.32006307,  1.12528867,  0.00697176,  1.53316054, -0.79126109],
       [-1.69347021, -0.8643602 , -1.60069644,  1.21779868, -1.86526636]])

### 8). Convert 3 arrays into a 1d array.                          2 points

arr1: 0,1,2

arr2: 3,4,5,6

arr3: 7,8,9

Generate the 3 arrays by numpy arange()

Desired Output:

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr1=np.arange(3)
arr2=np.arange(3,7)
arr3=np.arange(7,10)
print("arr1 : ",arr1)
print("arr2 :",arr2)
print("arr3 :",arr3)
output=np.concatenate((arr1,arr2,arr3))
print("Desired output : ")
output


arr1 :  [0 1 2]
arr2 : [3 4 5 6]
arr3 : [7 8 9]
Desired output : 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 9). Get all items between 15 and 55 from aa, math expression: [15,55].                  2 points

The aa is uniformly distributed integers in a 1D array (size=20) with given values (<100). Requires defining a seed.

In [25]:
np.random.seed(100)
aa=np.random.randint(0, 100, 20)
print("The value of aa:")
print(aa)

ll=[]
for element in aa:
    if element in range(16,56):
        ll.append(element)
print("Items between 15 to 55 are: \n",ll)


The value of aa:
[ 8 24 67 87 79 48 10 94 52 98 53 66 98 14 34 24 15 60 58 16]
Items between 15 to 55 are: 
 [24, 48, 52, 53, 34, 24, 16]


### 10). Get the positions where elements of a and b match.                 2 points

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])     
position=np.where(a==b)
print("Positions are : ",position)

Positions are :  (array([1, 3, 5, 7]),)


### 11). Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1. 

In [27]:
y=np.arange(21)
y[1::2]=-1             
y

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20])

### 12). Use two addition functions of Numpy to add every element in a 1D array of size 10 and finally get one value.; and set a timer to time the two addition functions to see which one is faster.   

In [28]:
x=np.random.randint(20,size=(10)) 
x
y=np.sum(x)
print(y)
t1 = %timeit y
print(t1)

total = 0
for i in x:
    total = i + total
print(total)

t2=%timeit total
print(t2)

71
22 ns ± 0.0562 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
None
71
21.8 ns ± 0.136 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
None


### 13). Subtract the mean of each row of a matrix X. X is a random 2D 5x10 array. 

In [29]:
np.random.seed(69)
a1=np.random.randint(100,size=(5,10))                                                  
b= a1 - a1.mean(axis=1, keepdims=True)
print(b)

[[  3.7  24.7  22.7  39.7   4.7 -30.3  -1.3 -28.3 -41.3   5.7]
 [ 39.1 -19.9  38.1  30.1 -45.9 -20.9  17.1  -4.9 -54.9  22.1]
 [ -9.3 -24.3 -46.3  50.7  -9.3 -24.3  -1.3  41.7  26.7  -4.3]
 [-25.6 -13.6  -5.6  37.4 -34.6 -27.6   0.4  21.4  20.4  27.4]
 [-38.8 -38.8  38.2   8.2  -4.8  -7.8 -36.8  40.2  30.2  10.2]]


### 14) Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, how to get sum over the last two axis at once?

In [30]:
arr = np.random.randint(0,10,(3,4,3,4))
print("The 4D array is:\n", arr)
sum = arr.sum(axis=(-2,-1))
print("Sum of last 2 axis:\n",sum)


The 4D array is:
 [[[[2 1 2 5]
   [8 0 9 2]
   [1 3 7 5]]

  [[0 0 1 0]
   [8 9 7 5]
   [4 9 9 9]]

  [[2 7 1 5]
   [5 3 4 1]
   [9 3 6 7]]

  [[3 1 5 9]
   [9 4 0 5]
   [0 3 8 8]]]


 [[[7 2 7 0]
   [9 1 0 7]
   [0 2 3 9]]

  [[2 9 7 8]
   [3 0 1 1]
   [3 1 5 2]]

  [[1 3 9 8]
   [8 6 8 5]
   [3 5 8 7]]

  [[2 9 3 9]
   [2 1 4 3]
   [3 0 9 2]]]


 [[[9 4 6 4]
   [9 0 1 7]
   [7 9 1 1]]

  [[6 9 2 5]
   [3 5 1 6]
   [6 1 1 3]]

  [[4 0 0 7]
   [3 5 4 1]
   [9 3 3 8]]

  [[0 7 3 0]
   [6 4 9 9]
   [6 5 1 5]]]]
Sum of last 2 axis:
 [[45 61 53 55]
 [47 42 71 47]
 [58 48 47 55]]


### 15). Use np.put to randomly place 3 numbers (which can be any value, like 5) in a 2D 10x10 zero array:

In [31]:
x=np.zeros((10,10))
print(x)
y=np.random.choice(10,3,replace=False)  
print(y)
z=np.put(x, y, np.random.randint(10,size=(10,10)) ,mode = 'raise')
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[7 5 9]
[[0. 0. 0. 0. 0. 5. 0. 1. 0. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Indexing and Slicing:

### 1) Given a 1d array: [ 3, 6, 9, 25, 10, 8]                      4 points

(1) To get all elements except the first:

(2) To get all elements except the last:

(3) To get every other element of the array (operation from the first element):

(4) To reverse the array:

In [32]:
x=[ 3, 6, 9, 25, 10, 8]
y=np.array(x)

y1=y[1:]
print("All elements except the first : \n",y1)                 
y2=y[:5]
print("All elements except the last : \n",y2)
y3=y[::2]
print("Every other element of the array (operation from the first element) : \n",y3)
y4=y[::-1]
print("Reverse the array : \n",y4)

All elements except the first : 
 [ 6  9 25 10  8]
All elements except the last : 
 [ 3  6  9 25 10]
Every other element of the array (operation from the first element) : 
 [ 3  9 10]
Reverse the array : 
 [ 8 10 25  9  6  3]


### 2) Multidimensional Arrays:               4 points

(1) create an array with the components as 0-31 and the shape is (8,4).

(2) set the 3rd element in the 1st row to 0.

(3) print out the second column.

(4) Get the 3x3 region from the array:

([ 9, 10, 11],

 [13, 14, 15],

 [17, 18, 19]])

In [33]:
x=np.arange(32).reshape(8,4)
print("An array with the components as 0-31 and the shape is (8,4 :")
print(x)
x[0,2]=0
print("Set the 3rd element in the 1st row to 0 : ")
print((x))
print("Second column : ",x[:,1])
print("3x3 region from the array :")
print(x[2:5,1:])

An array with the components as 0-31 and the shape is (8,4 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Set the 3rd element in the 1st row to 0 : 
[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Second column :  [ 1  5  9 13 17 21 25 29]
3x3 region from the array :
[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


### 3) Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy "slicing" method to realize.                4 points

[[0. 1. 0. 1.]

 [1. 0. 1. 0.]

 [0. 1. 0. 1.]

 [1. 0. 1. 0.]]

In [34]:
x=np.ones((4,4))
x[::2,::2]=0            
x[1::2,1::2]=0
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

### 4) Swap the first two rows of the array: aa = np.arange(20).reshape(5,4) 

In [35]:
aa = np.arange(20).reshape(5,4)
print(aa)
aa[[1, 0], :] = aa[[0, 1], :]           
aa

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Broadcasting in Practice:

### 1) Given 2 arrays:                                                        2 points

a_2d : [[3,3,3],[4,4,4],[5,5,5]]

b_1d : [1,2,3]

Do the subtraction so that the result is:

[[2 2 2]

 [2 2 2]

 [2 2 2]]

In [36]:
a_2d = [3,3,3],[4,4,4],[5,5,5]
b_1d = [1,2,3]
a1=np.array(a_2d)
a2=np.array(b_1d)            
a3=a1-a2[:,None]
a3


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

### 2). Write a 6x6 matrix for multiplication table:          8 points

- by using numpy broadcasting (4 points)

- by using Python nested for-loop (4 points).

Desired output:

array([[ 1,  2,  3,  4,  5,  6],

       [ 2,  4,  6,  8, 10, 12],

       [ 3,  6,  9, 12, 15, 18],

       [ 4,  8, 12, 16, 20, 24],

       [ 5, 10, 15, 20, 25, 30],

       [ 6, 12, 18, 24, 30, 36]])

In [37]:
a=np.arange(1,7)
b=np.arange(1,7)
print(a[:, None] * b)

y=[1,2,3,4,5,6]
res=[]
for i in range(6):
    res.append([x*(i+1) for x in a])   
print("Loops : ")
res
    

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
Loops : 


[[1, 2, 3, 4, 5, 6],
 [2, 4, 6, 8, 10, 12],
 [3, 6, 9, 12, 15, 18],
 [4, 8, 12, 16, 20, 24],
 [5, 10, 15, 20, 25, 30],
 [6, 12, 18, 24, 30, 36]]

### 3) For an arbitrary array of dimension (5,5,3), consider multiplying it by an arbitrary array with dimensions (5,5).  

In [38]:
np.random.seed(0)
x = np.random.randint(10, size=(5, 5, 3))
y = np.random.randint(10, size=(5, 5))
print("x: ",x)
print()
print("y : ",y)                          
print()
print("x*y : ",x*y[:,:,None])

x:  [[[5 0 3]
  [3 7 9]
  [3 5 2]
  [4 7 6]
  [8 8 1]]

 [[6 7 7]
  [8 1 5]
  [9 8 9]
  [4 3 0]
  [3 5 0]]

 [[2 3 8]
  [1 3 3]
  [3 7 0]
  [1 9 9]
  [0 4 7]]

 [[3 2 7]
  [2 0 0]
  [4 5 5]
  [6 8 4]
  [1 4 9]]

 [[8 1 1]
  [7 9 9]
  [3 6 7]
  [2 0 3]
  [5 9 4]]]

y :  [[4 6 4 4 3]
 [4 4 8 4 3]
 [7 5 5 0 1]
 [5 9 3 0 5]
 [0 1 2 4 2]]

x*y :  [[[20  0 12]
  [18 42 54]
  [12 20  8]
  [16 28 24]
  [24 24  3]]

 [[24 28 28]
  [32  4 20]
  [72 64 72]
  [16 12  0]
  [ 9 15  0]]

 [[14 21 56]
  [ 5 15 15]
  [15 35  0]
  [ 0  0  0]
  [ 0  4  7]]

 [[15 10 35]
  [18  0  0]
  [12 15 15]
  [ 0  0  0]
  [ 5 20 45]]

 [[ 0  0  0]
  [ 7  9  9]
  [ 6 12 14]
  [ 8  0 12]
  [10 18  8]]]


# Others

### 1) Find the closest value from a given value 0.5 in an arbitrary array with values 0-1.

In [39]:
value = 0.5

def closest(array, value):
    index_min = (np.abs(array - value)).argmin()
    return array[index_min]

array = np.random.random(10)
print("Array : ",array)

print("\n Nearest Value : ",closest(array, value))

Array :  [0.971945   0.87819347 0.50962438 0.05571469 0.45115921 0.01998767
 0.44171092 0.97958673 0.35944446 0.48089353]

 Nearest Value :  0.5096243767199001


### 2) Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [40]:
Z = np.arange(1,15,dtype=int)

def generate(x, window):
    y1 = (x.size - window + 1, window)
    y2 = (x.itemsize, x.itemsize)
    return np.lib.stride_tricks.as_strided(x, shape=y1, strides=y2)
    
R = generate(Z, 4)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])