In [1]:
import numpy as np


In [4]:
x = np.arange(1,7).reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.array([2,3,4,5,5,6])

array([2, 3, 4, 5, 5, 6])

In [6]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
#arange(start,end,step)
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
#linspace - equal distance (start,end,divided into)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create a 3x3 array of uniformly distributed
        # random values between 0 and 1
np.random.random((3,3))

array([[0.45535805, 0.17924327, 0.84185015],
       [0.30839854, 0.03384302, 0.38839579],
       [0.91635414, 0.35751979, 0.88947391]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[1, 1, 3],
       [9, 1, 2],
       [4, 8, 0]])

In [20]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.seed(0)
x1= np.random.randint(10,size=6)
x2= np.random.randint(10, size=(3,4))
x3= np.random.randint(10,size=(2,2,4))

In [29]:
#Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):
print("X3 number of dimesnsions",x3.ndim)
print("X3 shape",x3.shape)
print("x3 size",x3.size)
print(x3.dtype)


X3 number of dimesnsions 3
X3 shape (2, 2, 4)
x3 size 16
int64


In [31]:
#Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array:
print("size of each arrays element",x3.itemsize)
print("size of the array",x3.nbytes)

size of each arrays element 8
size of the array 128


In [41]:
#nbytes is equal to itemsize times size
print(".size*.itemsize",x3.size*x3.itemsize)
print("nbytes",x3.nbytes)


.size*.itemsize 128
nbytes 128


### Array Indexing: Accessing Single Elements

In [43]:
x1


array([5, 0, 3, 3, 7, 9])

In [47]:
x1[0]

5

In [48]:
x1[-1]

9

In [49]:
x1[-2]

7

In [52]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [56]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [59]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [60]:
x[4:8] # subarray

array([4, 5, 6, 7])

In [61]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [62]:
x[1::2] # every other element starting 1

array([1, 3, 5, 7, 9])

In [63]:
x[::-1]# reverse all elements

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [67]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [70]:
x2[:2,:3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [75]:
x2[:3,::2] # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [76]:
x2[::-1,::-1] #subarray dimensions can even be reversed together

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [81]:
x2[:,2] #  3 column of x2

array([2, 8, 7])

In [82]:
x2[1,:]#  2 row of x2

array([7, 6, 8, 8])

#### Creating copies of arrays

In [84]:
x2_subCopy= x2[:2,:2].copy()
print(x2_subCopy)

[[3 5]
 [7 6]]


In [87]:
#If we now modify this subarray, the original array is not touched:
x2_subCopy[0,0]=42
print(x2_subCopy)
print("\nx2 :",x2)

[[42  5]
 [ 7  6]]

x2 : [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


#### Reshaping of Arrays


In [90]:
grid= np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. You can do this with the reshape method, or more easily by making use of the newaxis keyword within a slice operation:

In [97]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [98]:
# row vector via reshape
x.reshape((1, 3))
x

array([1, 2, 3])

In [99]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [100]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [101]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### Concatenation of arrays -  np.concatenate, np.vstack, and np.hstack.

In [102]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [103]:
z = [99, 99, 99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [105]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
# concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [111]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [112]:
# np.vstack (vertical stack) np.hstack (horizontal stack)

In [114]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

# vertically stack the arrays
np.vstack([grid, x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [116]:
# horizontally stack the arrays
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [128]:
### Splitting of arrays np.split, np.hsplit, and np.vsplit
# N split points lead to N + 1 subarrays
# np.dsplit will split arrays along the third axis.

In [118]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [119]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print(lower)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [127]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


## Computation on Arrays: Broadcasting

In [129]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [131]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [132]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [135]:
M = np.ones((2, 3))
a = np.arange(3)


In [136]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [137]:
a

array([0, 1, 2])

In [140]:
M.shape

(2, 3)

In [141]:
a.shape

(3,)

In [142]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [143]:
# right-side padding: you can do this explicitly by reshaping the array (we’ll use the np.newaxis

In [144]:
a[:, np.newaxis].shape

(3, 1)

## Centering an array

In [146]:
X = np.random.random((10, 3))
X

array([[0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 ],
       [0.46631077, 0.24442559, 0.15896958],
       [0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323],
       [0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.97676109],
       [0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299]])

In [147]:
Xmean = X.mean(0) #the mean of each feature using the mean aggregate across the first dimension:
Xmean

array([0.40028926, 0.45086729, 0.34027646])

In [150]:
# center the X array by subtracting the mean 
X_centered = X - Xmean
X_centered.mean(0)

array([-8.88178420e-17,  0.00000000e+00,  3.33066907e-17])